baseURL = "https://dot.is-a.dev/blog/"
languageCode = "ru-ru"
title = "Dott"
theme = "ink"

publishDir = "docs"

pygmentsCodeFences = true
pygmentsStyle = "friendly"

googleAnalytics = ""

[blackfriday]
hrefTargetBlank = true

[params]
customCSS = "css/custom.css"
subtitle = "не придумал, что я тут буду постить, но пусть будет"
disableDisqusTypes = ["page", "post"]
mainSections = ["page", "post"]

[[params.social]]
name = "Github"
icon = "github"
url = "https://github.com/Dott-rus/"

[[params.social]]
name = "Mail"
icon = "mail"
url = "mailto:dott.main@gmail.com"

[[params.social]]
name = "RSS"
icon = "rss"
url = "/blog/index.xml"
